# -*- mode: ruby -*-
# -*- coding: utf-8 -*-
# vi: set ft=ruby :

def install_plugin(plugin)
  system("vagrant plugin install #{plugin}") unless Vagrant.has_plugin? plugin
end

install_plugin('vagrant-notify-forwarder')
install_plugin('vagrant-fsnotify')

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/boxes/bionic64/versions/1.0.282/providers/virtualbox.box"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :public_network
  config.vm.synced_folder "../src", "/vagrant-data", mount_options: ['fmode=777', 'dmode=777'], fsnotify: true
  config.vm.provision :shell, inline: "mkdir -p /home/vagrant/mount_point/node_modules"
  config.vm.provision :shell, inline: "mkdir -p /vagrant-data/gulp/node_modules"
  config.vm.provision :shell, inline: "mount --bind /home/vagrant/mount_point/node_modules /vagrant-data/gulp/node_modules", run: "always"
  config.vm.provision :shell, :path => "bootstrap.sh"
end
